area_name: ALIKE

bbox_wgs84:
  left: 6.47
  right: 14.89
  top: 55.17
  bottom: 51.41

crs_proj_out: EPSG:25832  # target CRS for POIs output; should match the coordinate system used by the model / the zones file (OSM source CRS is always EPSG:4326 = GPS coordinates from OSM (WGS84))

exclude_osm_ids:
  - id: 119066859 # Alsterdorfer Anstalten = very large area of Diakonie containing many individual POIs
  - id: 93320362 # riesige Fläche auf Norderney, nicht unbedingt touristisch ausgebaut

percentile_imputation: 0.2 # If a POI has no area information but area is required for attractiveness calculation for this category, the area is imputed with the this percentile of the areas of all POIs of this category that have area information


paths:
  osmosis_bin: C:/Program Files (x86)/Osmosis/osmosis-0.49.2/bin
  osm_raw_base: data/osm-raw/germany-240101
  filter_dir: config/filters/DE
  osm_filtered_dir: data/osm-filtered
  buildings_input: //172.22.71.216/Unverschluesselt/ALIKE_temp/attractivities/region_Gebaeude_repariert_multipolygons_struktur.gpkg
  pois_root_dir: data/pois
  pois_dir_name: Export_Points_ALIKE
  zones_file: //ifv-fs.ifv.kit.edu/Forschung/Projekte/ALIKE_MOIA_Hochbahn_autonom/Work/GIS/Zelleinteilung/zellen_typ_1_2_3_4_25832.geojson
  attractiveness_output_root: //ifv-fs.ifv.kit.edu/Forschung/Projekte/ALIKE_MOIA_Hochbahn_autonom/Work/Daten/Attraktivitäten/Aufbereitung_Region_2026-05-05
  attractiveness_output_sub_attractiveness: attractiveness
  attractiveness_factors_json: config/locale/attractiveness_factors_DE_KIT-internal_ALIKE.json
  pois_config: config/locale/OSM2POIs_config_DE.yaml


eval:
  attractiveness_maps:
    zone_types: ["1", "2", "3", "4"]
    grid_cellsize_m_default: 1000
    grid_cellsize_m_by_type:
      "1": 1000
      "2": 2000
      "3": 5000
      "4": 5000
    make_html_maps: false
